application: zoyoeec
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: static/zoyoe.ico
  upload: static/zoyoe.ico

- url: /static
  static_dir: static

- url: /.*
  script: core.main.application

libraries:
- name: django
  version: latest
- name: lxml
  version: latest
- name: PIL
  version: latest

env_variables:
  DJANGO_SETTINGS_MODULE : 'core.settings'
